/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.services.UserBookingService;
import ticket.booking.util.UserServiceUtil;

import java.util.ArrayList;
import java.util.Scanner;
import java.util.UUID;

public class App {

    public static void main(String[] args) {

        System.out.println("Running Train Booking System");
        Scanner scanner = new Scanner(System.in);
        int option = 0;
        UserBookingService userBookingService;
        try {
            userBookingService = new UserBookingService();
        } catch (Exception e) {
            System.out.println("There is Something Wrong");
            return;
        }
        while (option != 7) {
            System.out.println("Please Select a Option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel Booking");
            System.out.println("7. Exit the App");
            option = scanner.nextInt();
            switch (option) {
                case 1:
                    System.out.println("Please Enter Username to signup");
                    String nameToSignup = scanner.next();
                    System.out.println("Please Enter Password to signup");
                    String passwordToSignUp = scanner.next();
                    User userToSignUp = new User(nameToSignup, passwordToSignUp, UserServiceUtil.hashPassword(passwordToSignUp),
                            new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignUp);
                    break;
                case 2:
                    System.out.println("Please Enter Username to login");
                    String nameToLogin = scanner.next();
                    System.out.println("Please Enter Password to login");
                    String passwordToLogin = scanner.next();
                    User userToLogin = new User(nameToLogin,passwordToLogin,UserServiceUtil.hashPassword(passwordToLogin),new ArrayList<>(),UUID.randomUUID().toString());
                    try{
                        userBookingService  = new UserBookingService(userToLogin);
                    }catch(Exception e){
                        return;
                    }
                    break;
                    case 3:
                    System.out.println("Fetch Booking Details");
                    userBookingService.fetchBooking();
                    break;
                case 4:
                    System.out.println("Search Source Station");
                    String source = scanner.next();
                    System.out.println("Search Destination Station");
                    String destination = scanner.next();
                    List<Train> trains = userBookingService.getTrains(source,destination);
                    int index = 1;
                    for(Train t : trains){
                        System.out.println(index="Train id : "+t.getTrainid())
                    }
            }
        }
    }
}

